set nocompatible
syntax enable " enable syntax highlight
set tabstop=4	" numbers of spaces of tab character
set shiftwidth=4	" numbers of spaces to (auto)indent
set expandtab
set scrolloff=4	" keep 3 lines when scrolling
set hlsearch	" highlight searches
set ruler	" show the cursor position all the time
set ttyfast	" smoother changes
set autoread " auto read when a file is changed from the outside
set showmatch " show matching bracets when text indicator is over them
set ai " auto indent
set si " smart indet
set showcmd " shows what you are typing as a command
colorscheme slate " cf3
set wildmenu " cool tab completion
set incsearch " incremental searching /
cmap w!! w !sudo tee > /dev/null %
set t_Co=256
set relativenumber
